#!/bin/bash
set -u


# Replace all http URLs with https if available


while read -r file; do
  # Find all URLs
  while read -r match; do
    url="$(echo "$match" | cut -d: -f2)"
    # Check if URL works with https
    if curl -sI "https:$url" > /dev/null; then
      # Switch URL to https
      echo "$file: https:$url"
      sed -i '' "s,http:$url,https:$url,g" "$file"
    fi
  done < <(grep -Ino 'http://[^") \]]*' "$file")
done < <(git ls-files)
