#!/usr/bin/env bash
set -e


name="$1"

if [ "$(which hugo)" = "" ]
then
  echo "Hugo is not installed. Get it at https://gohugo.io/"
  exit 1
fi

if [ "${name}" = "" ]
then
  echo "Name missing. Try: ./new some-name"
  exit 1
fi

rel="post/${name}.md"
path="content/${rel}"

hugo new ${rel}

# Drop draft line. Add description instead.
sed -e '4d' -i '' ${path}

$EDITOR ${path}
