#!/usr/bin/env sh
set -e


name="$1"

if [ "$(which hugo)" = "" ]
then
  echo "Hugo is not installed. Get it at https://gohugo.io/"
  exit 1
fi

if [ "${name}" = "" ]
then
  echo "Name missing. Try: ./new some-name"
  exit 1
fi

path="post/${name}.md"

hugo new -fyaml ${path}

# Drop draft line. Add summary instead.
sed $'3c\\\nsummary: |\n;3i\\\n\ \ ...\n' "content/${path}"
