#!/bin/sh
set -e


name=$1

if [ -z $(which hugo) ]; then
  echo "Hugo is not installed. Get it at https://gohugo.io/"
  exit 1
fi

if [ -z ${name} ]; then
  echo "Name missing. Try: ./new some-name"
  exit 1
fi

path=post/${name}.md

hugo new -fyaml ${path}

# Drop draft line. Add summary instead.
sed -i '3s/.*/summary: |\n  .../' content/${path}
